server:
  port: 8090

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

    hibernate:
      ddl-auto: create


logging:
  level:
    org.hibernate.SQL: debug
